/*RAKSHA*/
/*
THIS IS BASICALLY A FALL-DETECTION ALGORITHM WHICH DETECTS A FALL USING AN ACCELEROMETER 
WHEN THE ACCELROMETER DETECTS A FREE FALL, THE INTERRUPT PIN BECOMES HIGH AND THIS SIGNAL SENT BY THE INTERRUPT IS SENT AS A DISTRESS SIGNAL TO THE ANDROID DEVICE AND HENCE IS  USED IN ORDER TO DETECT FALL.

MCU-ARDUINO UNO
COMMUNICATION MODULE-BLE HC05
ACCELEROMTER-MMA 7361
LAST MODIFIED DATE - 29/05/2017   
*/
int accel_interrupt= 4; /* ARDUINO DIGITALPIN PIN 4 IS USED TO READ THE INTERRUPT FORM THE ACCEL */
int accel_state=0;  /*THE ACCELEROMETRE STATE IS INTILIZED(ASSUMED) TO BE - 0(LOW) AT THE BEINING  */
int on_hand_detect=5;/*ARDUINO DIGITAL PIN 5 IS USED TO READ THE CURRENT STATE OF BAND(WHETHER CONNECTED OR NOT CONNECTED )*/
int on_hand_state ;    /*THE ONHAND STATE IS USED TO READ THE PROXIMITY STATE*/
void setup() {
  pinMode(accel_interrupt,INPUT); /* THE accel_interrupt PIN IS INTILIZED AS INPUT TO THE ARDUINO */
  Serial.begin(9600);/*BAUD-RATE IS SET TO 9600 WHICH IS SPCIFIED BY hc-05 MODULE */
  pinMode(on_hand_detect,INPUT);/*THE on_hand_detect PIN IS INTILIZED AS INPUT TO THE ARDUINO*/

}

/*MAIN LOOP START HERE,IT IS AN INFINTE LOOP */
void loop() {

  /*CHECK WHEATHER THE BAND IS ON HAND OR NOT */
  on_hand_state=digitalRead(on_hand_detect);
 /* IF IT IS ON HAND THEN PROCEED  OR ELSE STAY ON BATTERY SAVING MODE OR COMPLETLY OFF MODE */
  if(on_hand_state== HIGH){
         /*CHECK WHETHER THE BLUETOOTH IS CONNECTED TO AN ANDROID OR NOT THIS ALLOWS US TO SAVE POWER WHILE THE BAND IS NOT CONNECTED TO ANY DEIVCE  */
        if(Serial.available()>0){
             accel_state = digitalRead(accel_interrupt);
             if(accel_state == HIGH){
             Serial.write(1);/*AT PRESENT DISTRESS SIGNAL IS A STRING WHCIH IS "1",FUTURE IT WILL BE  TRANSFERED AS A DATA PACKET  */
             }
        }
  }
}
